# Generated by Django 4.0.1 on 2022-12-12 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0007_subuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubUser',
            new_name='Employee',
        ),
    ]
