# Generated by Django 4.0.1 on 2022-12-12 07:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0008_rename_subuser_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='UserDetail',
        ),
    ]
